name: NaviCompass
author: Xenophilicy
version: 2.1.1
main: Xenophilicy\NaviCompass\NaviCompass
api: 3.0.0
Description: View all your servers or worlds in a list using FormAPI!
commands:
  navicompass:
    description: Get info on NaviCompass